import * as workshop from '../dist/workshop.js';
import * as skills from '../dist/skills.js';
import * as backup from '../dist/backup.js';
import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {webcrypto} from 'node:crypto';
import {makeDeck,explanation} from '../dist/engine.js';import * as progress from '../dist/progress.js';import {Session} from '../dist/session.js';
import * as gameplay from '../dist/gameplay.js';
import * as mathGames from '../dist/math-games.js';
import * as reports from '../dist/analysis.js';
class GameAudio{constructor(){this.prefs={music:false,effects:true};}menu(){}start(){}stop(){}finish(){}play(){}tick(){}set(){}suspend(){}resume(){}}
const source=fs.readFileSync(new URL('../dist/app.js',import.meta.url),'utf8').replace(/^import .*\n/gm,'');
function harness(storage,legacy=true){let now=1000000;class ClockDate extends Date{static now(){return now;}}const el=()=>({innerHTML:'',dataset:{},classList:{toggle(){}},setAttribute(){},querySelectorAll:()=>[],querySelector:x=>controls[x]||null,focus(){}});const app=el(),controls={'#app':app,'#player-nav':el(),'#main-nav':el()};const context=vm.createContext({...progress,...gameplay,...reports,...mathGames,...workshop,...skills,...backup,offlineStatus:()=>({ready:false,waiting:false}),initOffline(){},applyOfflineUpdate(){},checkForUpdates(){},protectSaves(){},setTimeout:()=>1,GameAudio,Date:ClockDate,setInterval:()=>1,clearInterval(){},Session,makeDeck,explanation,drawAvatar(){},crypto:webcrypto,structuredClone,window:{localStorage:storage,scrollTo(){},addEventListener(){}},document:{body:{dataset:{}},querySelector:x=>controls[x]||null,querySelectorAll:()=>[],addEventListener(){}}});vm.runInContext(source,context);if(legacy)vm.runInContext("mode='parent';format='typing';timed=false;timeLimitMs=300000;roundSize=10;",context);return {run:s=>vm.runInContext(s,context),html:()=>app.innerHTML,input:(id,value)=>controls[id]={value,focus(){}},advance:ms=>now+=ms};}
test('create, customize, finish, reload and switch between independent players',()=>{let raw;const storage={getItem:()=>raw,setItem:(k,v)=>raw=v};const h=harness(storage);
 assert.match(h.html(),/Who’s playing/);h.run('act("new");editor.name="Nova";editor.avatar.accessory="cap";savePlayer();');assert.match(h.html(),/Where will we explore, Nova/);
 h.run('act("clear");act("table:5");act("start");act("wrong");');assert.match(h.html(),/LET’S BUILD IT TOGETHER/);h.run('act("undo");');assert.doesNotMatch(h.html(),/LET’S BUILD IT TOGETHER/);
 h.run('act("wrong");act("next");while(page==="play"){act("right");act("next");}');assert.match(h.html(),/Achievement unlocked/);
 let data=JSON.parse(raw);assert.equal(data.players[0].runs.length,1);assert.equal(data.players[0].runs[0].answers.length,11);assert.equal(data.players[0].runs[0].answers.filter(x=>x.retry).length,1);
 h.run('act("reports");');assert.match(h.html(),/90%/);assert.match(h.html(),/Mission history/);
 const again=harness(storage);assert.match(again.html(),/Where will we explore, Nova/);assert.equal(again.run('player().avatar.accessory'),'cap');
 again.run('act("players");act("new");editor.name="Orbit";savePlayer();');assert.equal(again.run('player().runs.length'),0);again.run('act("start");act("right");act("leave");act("discard");');assert.equal(again.run('player().runs.length'),0);
 again.run('act("choose:"+save.data.players[0].id);');assert.equal(again.run('player().runs.length'),1);
});
test('nickname markup is escaped and duplicate nicknames cannot overwrite profiles',()=>{let raw;const storage={getItem:()=>raw,setItem:(k,v)=>raw=v},h=harness(storage);h.run('act("new");editor.name="<img onerror=x>";savePlayer();');assert.doesNotMatch(h.html(),/<img onerror=x>/);h.run('act("new");editor.name="<img onerror=x>";savePlayer();');assert.match(h.html(),/already has a save slot/);assert.equal(JSON.parse(raw).players.length,1);});
test('studio saves expanded choices, resets draft changes and leaves history intact',()=>{let raw;const storage={getItem:()=>raw,setItem:(k,v)=>raw=v},h=harness(storage);
 h.run('act("new");editor.name="Comet";act("hair:5");act("pattern:jersey");savePlayer();act("start");while(page==="play"){act("right");act("next");}');
 h.run('act("edit:"+player().id);act("hair:3");act("reset-avatar");');assert.equal(h.run('editor.avatar.hair'),5);assert.equal(h.run('editor.avatar.style'),'jersey');
 h.run('act("shuffle-avatar");');assert.ok(h.run('editor.avatar.hair>=0&&editor.avatar.hair<6'));h.run('act("reset-avatar");savePlayer();');
 const again=harness(storage);assert.equal(again.run('player().avatar.hair'),5);assert.equal(again.run('player().runs.length'),1);
});
test('bot poses follow feedback and correction shows exact equal groups',()=>{const h=harness(memoryStorage());h.run('act("new");editor.name="Comet";savePlayer();act("start");session=new Session([{a:5,b:5}]);render();');assert.match(h.html(),/bot-sprite idle/);
 h.run('act("wrong");');assert.match(h.html(),/bot-sprite teach/);assert.equal((h.html().match(/class="power-pack"/g)||[]).length,5);assert.equal((h.html().match(/<i><\/i>/g)||[]).length,25);assert.match(h.html(),/5 \+ 5 \+ 5 \+ 5 \+ 5 = 25/);
 h.run('act("undo");act("right");');assert.match(h.html(),/bot-sprite cheer/);
});
test('solo typing validates, scores once, teaches mistakes and blocks parent controls',()=>{const h=harness(memoryStorage());h.run('act("new");editor.name="Asher";savePlayer();mode="solo";act("start");session=new Session([{a:5,b:5}]);render();');assert.match(h.html(),/answer-form/);assert.doesNotMatch(h.html(),/data-action="right"/);
 h.run('act("right");act("wrong");submitAnswer("");');assert.equal(h.run('session.feedback'),null);h.run('submitAnswer("20");submitAnswer("25");');assert.equal(h.run('session.feedback'),false);assert.equal(h.run('session.submitted'),20);assert.match(h.html(),/5 \+ 5 \+ 5 \+ 5 \+ 5 = 25/);
 h.run('act("next");submitAnswer("25");act("next");');assert.equal(h.run('player().runs[0].answers.length'),2);assert.equal(h.run('player().runs[0].answers[1].ok'),true);assert.equal(h.run('player().runs[0].mode'),'solo');
});
test('mixed solo alternates stable three-option questions with typing',()=>{const h=harness(memoryStorage());h.run('act("new");editor.name="Asher";savePlayer();mode="solo";format="mixed";act("start");session=new Session([{a:0,b:0},{a:9,b:9}]);render();');assert.match(h.html(),/answer-form/);h.run('submitAnswer("0");act("next");');assert.match(h.html(),/choice-answers/);assert.equal((h.html().match(/class="answer-choice"/g)||[]).length,3);const before=h.run('JSON.stringify(choices.get(1))');h.run('render();');assert.equal(h.run('JSON.stringify(choices.get(1))'),before);h.run('act("answer:81");act("next");');assert.equal(h.run('player().runs[0].answers.filter(a=>a.ok).length'),2);
});
test('timed solo rejects answers at deadline, does not score unanswered cards, and stops discarded timers',()=>{const h=harness(memoryStorage());h.run('act("new");editor.name="Asher";savePlayer();mode="solo";timed=true;act("start");');h.advance(299999);h.run('submitAnswer(String(session.card.a*session.card.b));act("next");');h.advance(1);h.run('submitAnswer(String(session.card.a*session.card.b));');assert.equal(h.run('player().runs[0].answers.length'),1);assert.equal(h.run('player().runs[0].timed'),true);h.run('act("missions");act("start");act("leave");act("discard");');h.advance(300000);h.run('tickClock();');assert.equal(h.run('timer'),null);assert.equal(h.run('player().runs.length'),1);
});

function memoryStorage(){let value=null;return {getItem:()=>value,setItem:(key,next)=>value=next};}
test('trial stops immediately on its last answer and records completion time without repeats',()=>{const h=harness(memoryStorage());h.run('act("new");editor.name="Asher";savePlayer();timed=true;selected=[5];act("start");');assert.equal(h.run('session.queue.length'),10);h.advance(65000);h.run('for(let i=0;i<9;i++){act("wrong");act("next");}');assert.equal(h.run('session.queue.length'),10);assert.equal(h.run('page'),'play');h.advance(345);h.run('act("right");');assert.equal(h.run('page'),'finish');assert.equal(h.run('run.elapsedMs'),65345);assert.equal(h.run('run.endReason'),'completed');assert.equal(h.run('run.answers.length'),10);assert.equal(h.run('timer'),null);assert.match(h.html(),/First completion record/);assert.match(h.html(),/10%/);h.run('tickClock();');assert.equal(h.run('player().runs.length'),1);});
test('expiry includes pending answer once and a late final answer cannot create a record',()=>{const h=harness(memoryStorage());h.run('act("new");editor.name="Asher";savePlayer();timed=true;selected=[5];act("start");act("right");');h.advance(300100);h.run('tickClock();tickClock();');assert.equal(h.run('run.answers.length'),1);assert.equal(h.run('run.elapsedMs'),300000);assert.equal(h.run('run.endReason'),'expired');assert.doesNotMatch(h.html(),/First completion record/);});



test('new player lands on a math hub with requested defaults and configurable timers',()=>{const h=harness(memoryStorage(),false);h.run('act("new");editor.name="Asher";savePlayer();');assert.match(h.html(),/STARWAY MISSION CONTROL/);for(const op of ['multiply','add','subtract'])assert.match(h.html(),new RegExp('data-action="game:'+op+'"'));assert.equal(h.run('mode'),'solo');assert.equal(h.run('format'),'choice');assert.equal(h.run('roundSize'),'all');assert.equal(h.run('timeLimitMs'),300000);h.run('act("game:add");');assert.match(h.html(),/All 20 available questions/);assert.match(h.html(),/value="60000"/);assert.match(h.html(),/value="180000"/);assert.match(h.html(),/value="300000" selected/);assert.doesNotMatch(h.html(),/id="timed"/);});
test('all arithmetic variants support both controllers and every timer with short or full sets',()=>{for(const op of ['add','subtract'])for(const level of ['two','three'])for(const minutes of [1,3,5])for(const controller of ['parent','solo']){const h=harness(memoryStorage(),false);h.run('act("new");editor.name="Asher";savePlayer();');h.run('act("game:'+op+'");variant="'+level+'";mode="'+controller+'";timeLimitMs='+minutes+'*60000;roundSize=10;start();');assert.equal(h.run('session.queue.length'),10);h.advance(5000);h.run('while(page==="play"){if(run.mode==="solo")submitAnswer(String(result(session.card)));else act("right");if(page==="play")act("next");}');assert.equal(h.run('run.answers.length'),10);assert.equal(h.run('run.elapsedMs'),5000);assert.equal(h.run('run.endReason'),'completed');assert.match(h.html(),/First completion record/);h.run('act("reports");act("detail:"+run.id);');assert.match(h.html(),/100%/);assert.doesNotMatch(h.html(),/undefined|NaN/);}});
test('zero borrowing teaches on screen, retries keep subtraction, and expiry saves partial results',()=>{const h=harness(memoryStorage(),false);h.run('act("new");editor.name="Asher";savePlayer();act("game:subtract");timed=false;timeLimitMs=0;format="typing";start();session=new Session([{a:300,b:124,operation:"subtract",variant:"three"}]);submitAnswer("184");');assert.match(h.html(),/Trade 1 hundred for 10 tens/);assert.match(h.html(),/place-trade/);h.run('act("next");submitAnswer("176");act("next");');assert.equal(h.run('run.answers[1].operation'),'subtract');h.run('act("game:add");timeLimitMs=60000;timed=true;start();submitAnswer(String(result(session.card)));');h.advance(60000);h.run('tickClock();');assert.equal(h.run('run.endReason'),'expired');assert.equal(h.run('run.elapsedMs'),60000);assert.equal(h.run('run.answers.length'),1);assert.match(h.html(),/19<\/strong><span>not answered/);});

test('blitz setup covers all combinations, teaches making ten, and replay keeps settings',()=>{const h=harness(memoryStorage(),false);h.run('act("new");editor.name="Asher";savePlayer();act("blitz");');assert.match(h.html(),/All 81 available/);h.run('timeLimitMs=60000;start();session=new Session([{a:8,b:7,operation:"add",variant:"blitz"},{a:4,b:3,operation:"add",variant:"blitz"}],{retryMisses:false});run.totalFacts=2;submitAnswer("14");');assert.match(h.html(),/Make a ten/);assert.match(h.html(),/Split 7 into 2 and 5/);h.run('act("next");submitAnswer("7");');assert.equal(h.run('page'),'finish');assert.match(h.html(),/Play again with these settings/);h.run('act("replay");');assert.equal(h.run('run.variant'),'blitz');assert.equal(h.run('run.timeLimitMs'),60000);assert.equal(h.run('run.format'),'choice');assert.equal(h.run('session.queue.length'),81);});
test('interactive column UI records assisted answers honestly and keeps retries interactive',()=>{const h=harness(memoryStorage(),false);h.run('act("new");editor.name="Asher";savePlayer();act("game:add");format="columns";timed=false;timeLimitMs=0;start();session=new Session([{a:28,b:17,operation:"add"}]);lesson=null;render();');assert.match(h.html(),/column-form/);h.input('#column-digit','5');h.input('#carry-digit','0');h.run('submitColumn();');assert.match(h.html(),/carry 1/);h.input('#carry-digit','1');h.run('submitColumn();');h.input('#column-digit','4');h.input('#carry-digit','0');h.run('submitColumn();');assert.match(h.html(),/YOU WORKED IT OUT/);assert.equal(h.run('session.card.assisted'),true);h.run('act("next");');assert.match(h.html(),/column-form/);assert.equal(h.run('lesson.column'),0);});
test('block trades, skill launch, story map, and backup preview are connected',()=>{const h=harness(memoryStorage(),false);h.run('act("new");editor.name="Asher";savePlayer();');assert.match(h.html(),/map-stops/);assert.match(h.html(),/sprites\/controller.png/);h.run('act("game:add");format="blocks";timed=false;start();session=new Session([{a:8,b:7,operation:"add"}],{retryMisses:false});lesson=null;render();act("block-trade:0");act("block-check");act("next");');assert.equal(h.run('run.answers[0].ok'),true);h.run('act("reports");');assert.match(h.html(),/Parent dashboard/);h.run('act("skill:borrow-zero");start();');assert.ok(h.run('session.queue.every(f=>factSkills(f).includes("borrow-zero"))'));h.run('act("leave");act("discard");backupPending=readBackup(exportBackup(save.data));render();');assert.match(h.html(),/Add 0 player\(s\) and 0 mission/);h.run('act("backup-confirm");');assert.equal(h.run('player().runs.length'),1);});
