import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {GameAudio} from '../dist/audio.js';
const flush=()=>new Promise(resolve=>setImmediate(resolve));
function context(){const sources=[];return {sources,destination:{},resume:async()=>{},suspend:async()=>{},decodeAudioData:async b=>b,createGain:()=>({gain:{value:0},connect(){},disconnect(){}}),createBufferSource(){const s={connect(){},disconnect(){},start(){this.started=true;},stop(){this.stopped=true;this.onended?.();}};sources.push(s);return s;}};}
test('music is opt-in and toggles stop playback; stopping cancels pending sounds',async()=>{const ctx=context(),prefs=new Map(),sound=new GameAudio({getItem:k=>prefs.get(k),setItem:(k,v)=>prefs.set(k,v)},{contextFactory:()=>ctx,fetcher:async()=>({ok:true,arrayBuffer:async()=>new ArrayBuffer(1)})});await sound.start();await flush();assert.equal(ctx.sources.filter(s=>s.loop).length,0);sound.set('music',true);await flush();assert.equal(ctx.sources.filter(s=>s.loop&&s.started).length,1);sound.set('music',false);assert.equal(ctx.sources.find(s=>s.loop).stopped,true);sound.set('effects',false);await sound.play('tick');assert.equal(ctx.sources.filter(s=>!s.stopped).length,0);sound.stop();assert.equal(sound.active,false);assert.equal(JSON.parse(prefs.get('star-quest.audio.v1')).music,false);
 let release;const slowCtx=context(),slow=new GameAudio({getItem:()=>null},{contextFactory:()=>slowCtx,fetcher:()=>new Promise(r=>release=r)});await slow.start();slow.stop();release({ok:true,arrayBuffer:async()=>new ArrayBuffer(1)});await flush();assert.equal(slowCtx.sources.length,0);
});
test('countdown ticks only once for each of the last ten seconds',()=>{const s=new GameAudio({getItem:()=>null}),calls=[];s.play=name=>calls.push(name);s.active=true;for(let n=15;n>=0;n--){s.tick(n);s.tick(n);}assert.equal(calls.length,10);s.stop();s.tick(8);assert.equal(calls.length,10);});
test('all audio files are valid unclipped PCM with the intended durations',()=>{for(const [name,seconds] of [['starlight-loop',32],['start',.75],['correct',.3],['learn',.38],['finish',1],['clear',1.1],['tick',.09]]){const b=fs.readFileSync(new URL('../dist/audio/'+name+'.wav',import.meta.url));assert.equal(b.toString('ascii',0,4),'RIFF');assert.equal(b.readUInt32LE(24),22050);assert.equal(b.readUInt16LE(34),16);assert.ok(Math.abs((b.length-44)/44100-seconds)<.001);let peak=0;for(let i=44;i<b.length;i+=2)peak=Math.max(peak,Math.abs(b.readInt16LE(i)));assert.ok(peak>0&&peak<30000);}});


