import {test} from 'node:test';import assert from 'node:assert/strict';
import {LocalSave,STORAGE_KEY,recordRun,summarize,earnedBadges,practiceDeck} from '../dist/progress.js';
import {Session} from '../dist/session.js';
function memory(){let value=null;return {getItem:()=>value,setItem:(k,v)=>value=v};}
const answer=(a,b,ok,retry=false)=>({a,b,ok,retry});
test('profiles and avatars survive reload with isolated histories',()=>{const storage=memory(),save=new LocalSave(storage);save.update(d=>d.players.push({id:'a',name:'One',avatar:{hair:2},runs:[]},{id:'b',name:'Two',runs:[]}));save.update(d=>recordRun(d.players[0],{id:'r',world:'cosmos',answers:[answer(5,5,true)]}));const reload=new LocalSave(storage);assert.equal(reload.data.players[0].avatar.hair,2);assert.equal(reload.data.players[0].runs.length,1);assert.equal(reload.data.players[1].runs.length,0);});
test('updates merge latest saved profiles from another tab',()=>{const storage=memory(),a=new LocalSave(storage),b=new LocalSave(storage);a.update(d=>d.players.push({id:'a',name:'One',runs:[]}));b.update(d=>d.players.push({id:'b',name:'Two',runs:[]}));assert.equal(new LocalSave(storage).data.players.length,2);});
test('corrupt saves remain untouched and progress stays usable in memory',()=>{const storage=memory();storage.setItem(STORAGE_KEY,'broken');const save=new LocalSave(storage);assert.ok(save.error);assert.equal(save.update(d=>d.players.push({id:'a',name:'One',runs:[]})),false);assert.equal(storage.getItem(), 'broken');assert.equal(save.data.players.length,1);});
test('storage quota failure does not silently claim successful saving',()=>{const save=new LocalSave({getItem:()=>null,setItem(){throw Error('quota');}});assert.equal(save.update(d=>d.activeId='a'),false);assert.ok(save.error);assert.equal(save.data.activeId,'a');});
test('retry achievements and first-try statistics stay distinct',()=>{const p={runs:[]},r={id:'r',world:'cosmos',answers:[answer(5,5,false),answer(6,6,true),answer(5,5,true,true)]};assert.deepEqual(recordRun(p,r),['first','comeback','crew']);assert.deepEqual(recordRun(p,r),[]);const s=summarize(p.runs);assert.equal(s.attempts,3);assert.equal(s.firstCorrect,1);assert.equal(s.firstAttempts,2);assert.equal(s.comebacks,1);assert.equal(s.tables[5].needs.size,0);assert.equal(p.runs.length,1);assert.ok(earnedBadges(p.runs).includes('comeback'));});
test('smart practice prioritizes latest missed facts within chosen tables',()=>{const p={runs:[{answers:[answer(5,5,false),answer(6,6,false),answer(5,6,true)]}]};const d=practiceDeck(p,[5],10);assert.deepEqual(d[0],{a:5,b:5});assert.equal(d.length,10);assert.ok(d.every(x=>x.a===5));assert.deepEqual(d[9],{a:5,b:6});});
test('missed cards return once after intervening cards, then terminate',()=>{const s=new Session(Array.from({length:5},(_,b)=>({a:5,b})));s.mark(false);s.next();assert.equal(s.queue.length,6);assert.deepEqual(s.queue[4],{a:5,b:0,retry:true});while(!s.complete){s.mark(false);s.next();}assert.equal(s.answers.length,10);assert.equal(s.answers.filter(x=>x.retry).length,5);});
test('undo restores both scores and scheduled retry queue',()=>{const s=new Session([{a:5,b:5},{a:6,b:6}]);s.mark(true);assert.equal(s.stars,1);s.undo();assert.equal(s.stars,0);s.mark(false);s.next();assert.equal(s.queue.length,3);s.undo();assert.equal(s.queue.length,2);assert.equal(s.position,0);assert.equal(s.answers.length,0);s.mark(true);s.mark(false);assert.equal(s.feedback,true);s.next();assert.equal(s.stars,1);});
test('an abandoned mission never enters the persisted history',()=>{const p={runs:[]},s=new Session([{a:1,b:2}]);s.mark(true);assert.equal(p.runs.length,0);});


