import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
const root=new URL('../dist/',import.meta.url),excluded=new Set(['sw.js','README.md','accessories.png','avatar-heads.png','cosmos.png','skylands.png','robot.png']);
function walk(url,prefix=''){return fs.readdirSync(url,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(new URL(e.name+'/',url),prefix+e.name+'/'):excluded.has(e.name)||e.name.endsWith('.txt')?[]:[prefix+e.name]);}
const assets=walk(root).sort(),hash=crypto.createHash('sha256');for(const f of assets)hash.update(fs.readFileSync(new URL(f,root)));const version=hash.digest('hex').slice(0,12);
const code=`// Generated by scripts/build-offline.mjs; regenerate after any asset or source change.
const PREFIX='star-quest:'+new URL(self.registration.scope).pathname+':',CACHE=PREFIX+'${version}';
const ASSETS=${JSON.stringify(['./',...assets.map(f=>'./'+f)])};
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS))));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith(PREFIX)&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('message',event=>{if(event.data?.type==='ACTIVATE')self.skipWaiting();});
self.addEventListener('fetch',event=>{const url=new URL(event.request.url);if(event.request.method!=='GET'||url.origin!==self.location.origin||!url.href.startsWith(self.registration.scope))return;event.respondWith((async()=>{const cache=await caches.open(CACHE);if(event.request.mode==='navigate'){return await cache.match('./index.html')||fetch(event.request);}return await cache.match(event.request)||fetch(event.request);})());});
`;
fs.writeFileSync(new URL('sw.js',root),code);console.log('Offline cache',version,assets.length,'assets');
